---
format: html
---

<!-- no title in YAML front matter because it will be covered by the navbar - use html heading instead -->
<h1 class="page-top">About Our Project</h1>

The “English Catalogue of Books (1912-1922) Database” represents publishing information for over 99,400 titles issued in England and Ireland between 1912 and 1922 as reported by publishers and recorded in editions of the ECB issued between 1913-1923 (catalogues were issued the year following the year they covered). Our data is based on OCR-generated text drawn from facsimiles of copies of the ECB held at Princeton University Libraries (1912–1918, 1920, 1922) and the New York Public Library (1919 and 1921), and made available through HathiTrust’s Digital Library. The dataset includes the following categories of information for each work (where available in the original catalogues): author name, title, book format, publisher, month of publication, year of publication. On this site, we offer options to search and visualize the dataset. 

